name: app_cotopaxi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  http: ^1.2.1
  #shared_preferences: ^2.2.2
  geolocator: ^7.1.1
  #permission_handler: ^8.1.1
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.2
  url_launcher: ^6.3.0
  permission_handler: ^11.3.0
  syncfusion_flutter_pdf: ^26.2.4
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  flutter_hooks: ^0.18.0
  flutter_spinkit: ^5.1.0
  lottie: ^3.1.2
  font_awesome_flutter: ^10.7.0
  qr_code_scanner: ^1.0.1
  audioplayers: ^6.0.0
  flutter_dotenv: ^5.1.0
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/setting.png
    - assets/icon/admin.png
    - assets/icon/personasAdmin.png
    - assets/icon/albergue.png
    - assets/icon/sitioSeguros.png
    - assets/icon/zonaRiesgo.png
    - assets/icon/qr_code_scanner.png
    - assets/.env
